# Generated by Django 3.2.4 on 2021-06-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_trackedrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
